from tkinter import *
import tkinter.scrolledtext

import csiszaoptions

images = []


def help1(appwin, options):
    helppopup = Toplevel(appwin)
    sct = tkinter.scrolledtext.ScrolledText(master=helppopup, font=(options.letterfont, 17), background="white")
    sct.pack(fill=BOTH, expand=1)

    sct.insert("1.0", "\n         CSISZA -  mn. mely csak öszvetételekben használtatik,\n"
                      "         s am. csiszoló.\n"
                      "         (A magyar nyelv szótára - Czuczor Gergely, Fogarasi János)\n\n\n"
                      "\n                                                Kezelési útmutató\n\n\n"
                      "\n"
                      "\n"
                      "      Azonnali játék\n\n\n"
                      "      A Fájl menü Új  játék menüpontjából néhány előre elkészített példa konfigurációs\n"
                      "      fájlból való választás után, az Indítás gomb megnyomásával kezdeményezhetjük,\n"
                      "      egyjátékos módban.\n\n\n"
                      "      Áttekintés\n\n\n"
                      "      A program indítása után néhány előre elkészített mintajátékból lehet választani.\n"
                      "      Egy játék kiválasztása után, azzal közvetlenül el lehet kezdeni játszani, de a\n"
                      "      tábla vagy a játékbeállítások meg is változtathatók, és szerkesztés után új\n"
                      "      játékként el is lehet menteni későbbi használatra. Van lehetőség teljesen új\n"
                      "      táblát létrehozni. Ekkor az eredetileg betöltött játék egyéb beállításai\n"
                      "      öröklődnek.\n"
                      "      A beállított játék játszható egyedül vagy 1-3 gépi játékos ellen. A gépi\n"
                      "      ellenfelek erőssége többféleképpen befolyásolható. Létezik egy hálózati játék\n"
                      "      opció is, de csak egyetlen számítógépen több kliensprogram csatlakoztatásával\n"
                      "      volt kipróbálva, internetes játékra valószínűleg nem alkalmas. Használata nem\n"
                      "      javasolt.\n"
                      "      A játékmód lehet normál, ekkor a játékosok egymás után következnek saját\n"
                      "      betűikből szót alkotni, vagy szimultán, ekkor minden játékos egy időben alkot\n"
                      "      szót közös betűkből, és a legmagasabb pontértékű kerül a táblára. Szimultán\n"
                      "      játékban lehetőség van rá, hogy mindenki külön táblán játsszon. (A játék a\n"
                      "      betűkkel működött így, azt hiszem.)\n"
                      "      Beállítható a gondolkodási idő és a kihúzott betűk száma. Az is beállítható,\n"
                      "      hogy az új szónak kapcsolódnia kell-e a már táblán lévőkkel. Megadható kezdő\n"
                      "      mező, amit az első szónak kötelezően fel kell használnia. Előre megadható, hogy\n"
                      "      hány fordulóból álljon a játék.\n"
                      "      A betűkészlet kezelésére 3 lehetőség áll rendelkezésre. A készlet minden\n"
                      "      esetben előre megadott számút tartalmaz az egyes betűkből, az eltérés az, hogy\n"
                      "      a táblára kerültekkel csökken-e a még kihúzhatók száma. Az alapeset a csökkenés,\n"
                      "      a másik két lehetőség között a különbség, hogy csak a táblára kerültek\n"
                      "      pótlódnak a kihúzható készletben, vagy a teljes tartó tartalma. (Az utolsó\n"
                      "      esetben, a tartón levő betűk készlete minden fordulóban teljesen kicserélődik.)\n"
                      "      Egy külön tartón az összes játékosnak rendelkezésére álló, közös betűk adhatók\n"
                      "      meg. Így például, lehet mindenkinek ugyanannyi dzsókere. (Egy betű csak vagy az\n"
                      "      egyik, vagy a másik tartóra legyen beállítva, egyébként összezavarodhat a\n"
                      "      program.) Az is beállítható, hogy ezek a betűk minden körben változatlan\n"
                      "      számban rendelkezésre álljanak.\n"
                      "      A felhasznált betűk pontértéke lehet állandó, vagy véletlenszerű. Állandó\n"
                      "      pontértékeknél egy véletlenszerű szorzó sorsolása is beállítható.\n"
                      "      A kirakott szavak érvényességének ellenőrzése történhet a mellékelt szótár\n"
                      "      alapján, vagy helyesírás-ellenőrző program által. (Utóbbi esetben gépi játékos\n"
                      "      nem állítható be.) Az érvényesség ellenőrzése történhet minden körben, vagy csak\n"
                      "      a játék végén. Ekkor azok a betűk, amik nem alkotnak érvényes szavakat\n"
                      "      megjelölhetők, és az eredmény megállapításakor nem számítanak.\n"
                      "      A dzsókerek a táblán a kívánt betűre cserélhetőek, vagy maradhatnak a táblán is\n"
                      "      dzsókerek, így vízszintesen és függőlegesen más-más betűt reprezentálhatnak.\n"
                      "      A dzsókerek felvehetik a becserélt betűhöz megadott pontértéket.\n"
                      "      A pontozás történhet csak a lerakott betűk irányába, a keresztirányú szavaknak\n"
                      "      ekkor is érvényeseknek kell lenniük, de a pontértékük nem számít.\n"
                      "      Jutalmak adhatók a lerakott betűk száma alapján, vagy a már táblán levő betűk\n"
                      "      felhasználásáért. Ha az érvényesség ellenőrzése csak a játék végén történik,\n"
                      "      akkor a szavak hossza alapján lehet jutalmazni. Jutalom adható a játékot\n"
                      "      befejező játékosnak, és pontlevonás történhet a megmaradt betűk alapján. A\n"
                      "      tábla egyes mezőihez is hozzá lehet rendelni 1-9 pontos jutalmat.\n\n\n"
                      "      A tábla felépítése\n\n\n"
                      "      A megadható legnagyobb táblaméret 99 x 99.  A méret vízszintes és függőleges\n"
                      "      irányban eltérhet.\n\n"
                      " "
                      "      A következő mezőtípusok adhatók meg:\n"
                      "              normál mező\n"
                      "              előre beírt betűt tartalmazó mező (ha ? karaktert adunk meg, akkor a\n"
                      "                                                 tábla betöltésekor véletlenszerűen\n"
                      "                                                 kapott betű kerül rá, ha pedig 0-9\n"
                      "                                                 közé eső számjegyet adunk meg, akkor\n"
                      "                                                 azok jutalompontszámként értelmezendők)\n"
                      "              a betű értékét kétszerező mező\n"
                      "              a betű értékét háromszorozó mező\n"
                      "              a szó értékét kétszerező mező\n"
                      "              a szó értékét háromszorozó mező\n"
                      "              fal\n\n"
                      "      Ha van beállítva kezdő mező, akkor azt két egymást metsző vonalszakasz jelzi.\n"
                      "      Egy új tábla létrehozása, vagy már létező szerkesztése a Beállítások menüből\n"
                      "      elérhető Tábla lap Szerkesztés és Új tábla gombjaival indítható.\n\n\n"
                      "      Ezen a lapon lehet beállítani a tábla mezőinek megfelelő színeket, a mezők\n"
                      "      méretét és térközét, az előre beírt betűk színét, betűtípusát és méretét, és\n"
                      "      a sorok betűjelekkel, az oszlopok számjelekkel való ellátását.\n\n"
                      "      Ha valamelyik színes négyzetre kattintunk, akkor a hozzá tartozó mezőtípus\n"
                      "      színét változtathatjuk meg.\n\n\n"
                      "      Bármilyen beállításbeli változtatás után - akkor is ha azok a Betűk vagy a\n"
                      "      Játék lapon szerepelnek -, amit szeretnénk a későbbiekben is használni,\n"
                      "      szükséges a Szerkesztés gomb majd a Rendben gomb használata, mert a\n"
                      "      beállítások fájlba írása csak ekkor történik meg.\n\n\n"
                      "      A betűk megjelenése\n\n\n"
                      "      A Betűk lapon a betűket hordozó négyzetek mérete, színe, a feliratok színe,\n"
                      "      betűtípusa és mérete adhatók meg.\n"
                      "      A következő betűnégyzettípusok adhatók meg:\n"
                      "              normál betű\n"
                      "              kétszeres értékű betű\n"
                      "              háromszoros értékű betű\n"
                      "              a szó értékét kétszerező betű\n"
                      "              a szó értékét háromszorozó betű\n"
                      "              cserére jelölt betű\n\n"
                      "      A betűnégyzetek értékének megjelenítése kikapcsolható. (Pl. ha minden\n"
                      "      lerakott betű ugyanannyit ér.)\n\n\n"
                      "      Beállítható elemek, melyekből a játékszabályok felépíthetők\n\n\n"
                      "Játékmódok\n\n"
                      "      A program a legtöbb beállítást az egyszemélyes játékokban támogatja, gép\n"
                      "      ellen jobbára csak az egyszerűbbek válaszhatók ki, vagy ha mégis, akkor\n"
                      "      nem működnek helyesen.\n\n"
                      "      Gép elleni játék 1-3 (akár különbözően beállított) ellenféllel indítható,\n"
                      "      a játékosok léphetnek egymásután vagy egyidejűleg (szimultán), a tábla\n"
                      "      pedig szimultán játékban lehet minden játékos számára eltérő (ahogy a\n"
                      "      játék előrehaladtával ugyanazokból a betűkből más-más szavakat raknak\n"
                      "      ki).\n"
                      "      A gép elleni játéknál a gondolkodási idő megadásakor figyelni kell arra,\n"
                      "      ha az itt és/vagy a Gépi ellenfelek lapon, az egyes gépi játékosoknál\n"
                      "      megadott érték túl alacsony, akkor a gép lépése elkéshet, és ez hibát\n"
                      "      okozhat. Minél több a tartókon levő betűk száma, és főleg a dzsókerek\n"
                      "      száma, annál több időre van szüksége a számítógépnek a szóalkotásra.\n"
                      "      (Ezt persze a számítógép teljesítménye is befolyásolja, régi gépeken\n"
                      "      több, új gépeken kevesebb időt igényelhet. Én egy 10 éves, 1 magos AMD\n"
                      "      Sempron 140 processzoros gépen készítettem, ennél valószínűleg ma már\n"
                      "      szinte csak erősebbek vannak használatban.)\n\n\n"
                      "Kapott betűk száma\n\n"
                      "      Egy lenyíló listában 3-20 darab véletlenszerűen sorsolt betű adható meg,\n"
                      "      ezek fognak megjelenni az első tartón. (Szemben az opcionális második\n"
                      "      tartóra kerülő közös betűkkel, amelyek előre meghatározottak.) Minél\n"
                      "      nagyobb számot állítunk be itt annál tovább tarthat a számítógépnek a\n"
                      "      szóalkotás.\n\n"
                      "Az új szónak kapcsolódni kell a már táblán levőkkel\n\n"
                      "      Itt dönthető el, hogy a táblára került szavaknak egy összefüggő szóláncot\n"
                      "      kell-e alkotnia. Ha be van állítva, a program hibaüzenet küld, és nem\n"
                      "      engedi kirakni a szabálytalanul lerakott betűket.\n\n"
                      "Meghatározott kezdő mezőre kell kerülnie az első szónak\n\n"
                      "      Ha be van állítva, és az első szót szabálytalanul próbáljuk lerakni,\n"
                      "      akkor azt nem engedi, és hibaüzenetet küld.\n\n"
                      "A körök száma előre meghatározott\n\n"
                      "      Egy játék háromféleképpen érhet véget. Adott számú forduló után,\n"
                      "      elfogynak a kihúzható betűk, a játékosok mindegyike adott számú körben\n"
                      "      passzol. (Passznak számít, ha adott körben nincs érvényes szava, vagy\n"
                      "      cserét kér, és ez így van beállítva.)\n\n"
                      "Cserék száma számítson bele a passzok számába\n\n"
                      "      Ha be van állítva, akkor a játék befejezése szempontjából a cserék száma\n"
                      "      is beleszámít a passzok számába.\n\n"
                      "A tábla látható területének korlátozása\n\n"
                      "      Akkor lehet értelme beállítani, ha a tábla nagyobb méretű, és\n"
                      "      véletlenszerű, szabálytalan alakzatban elhelyezett elemeket tartalmaz.\n"
                      "      (Pl. „falakból” készült akadályok, labirintusok, előre beírt,  adott vagy\n"
                      "      véletlenszerű betűk, felvehető bónuszpontszámok.) Gép elleni játékban nem\n"
                      "      állítható be.\n\n"
                      "A betűk kezelése\n\n"
                      "      A betűk sorsolása történhet egy adott, a kihúzott betűkkel csökkenő\n"
                      "      készletből, nem csökkenő készletből, és ez utóbbi módon úgy, hogy a tartó\n"
                      "      minden fordulóban teljesen kicserélődik.  A jobbra levő Készlet gombra\n"
                      "      kattintva a betűkészlet szerkeszthető.\n\n\n"
                      "      A típus V (vowel), ha a betű magánhangzó, C (consonant), ha a betű\n"
                      "      mássalhangzó, és N, ha  *, amit dzsókerként kezel a játék. Ennek a\n"
                      "      magánhangzók+dzsókerek és mássalhangzók arányának befolyásolásakor van\n"
                      "      jelentősége.\n\n"
                      "      Az Előfordulás oszlop jelenleg nincs használatban.\n\n"
                      "      A Csere oszlopban megadott betűkre cserélhető a Betű oszlopban megadott\n"
                      "      karakter, ha a táblára kerül.\n\n"
                      "A magánhangzók és mássalhangzók számának befolyásolása\n\n"
                      "      Ha be van állítva, akkor a program igyekszik a játékosok tartóján lévő\n"
                      "      magánhangzók+dzsókerek és mássalhangzók arányát javítani.\n\n"
                      "Közös betűk\n\n"
                      "      Ha bekapcsoljuk, akkor egy második tartón, az összes játékos számára az\n"
                      "      egész játék folyamán rendelkezésre álló betűk állíthatók be, az előző\n"
                      "      képen láthatóhoz hasonló táblázatban. Ehhez a készlet gombra kell\n"
                      "      kattintani. Ugyanaz a betű nem állítható be mind a két tartóra, mert az\n"
                      "      a tábla „szétesését” eredményezheti.\n\n"
                      "A közös betűk nem fogynak\n\n"
                      "      Ha be van állítva, akkor a közös betűk folyamatosan rendelkezésre állnak,\n"
                      "      akkor is, ha felhasználtuk az előző körben.\n\n"
                      "A betűk pontértéke\n\n"
                      "      Lehet a betűkészletnél megadott vagy 0-9 közötti véletlenszerű érték.\n\n"
                      "Véletlen szorzó\n\n"
                      "      Akkor állítható be, ha a pontértékek adottak.\n\n"
                      "A szavak érvényessége\n\n"
                      "      Beállítható, hogy csak a szótárban megtalálható szavakat fogadja el, vagy\n"
                      "      csak figyelmeztessen, ha nincs a szótárban valamelyik szó. Ez utóbbi gép\n"
                      "      elleni játékban nem állítható be. Egyszemélyes játékban történhet az\n"
                      "      ellenőrzés helyesírás-ellenőrző program használatával, ehhez persze annak\n"
                      "      telepítve kell lennie a számítógépen. Szükség van hozzá továbbá az enchant\n"
                      "      modulra is. Gép elleni játékban ez sem állítható be.\n\n"
                      "Csak a játék végén\n\n"
                      "      Egyszemélyes játékban lehetőség van arra, hogy az érvényesség szótár\n"
                      "      szerinti ellenőrzésére csak a játék végén kerüljön sor, így tetszőleges\n"
                      "      keresztrejtvény készíthető.\n\n"
                      "Dzsóker bármilyen betűt helyettesíthet a táblán\n\n"
                      "      Ha be van kapcsolva, akkor a lerakott dzsóker függőlegesen és vízszintesen\n"
                      "      más betűt reprezentálhat.\n\n"
                      "Dzsóker pontértéke is változik\n\n"
                      "      Ekkor a dzsóker nemcsak a becserélt betűt, de annak pontértékét is\n"
                      "      felveszi.\n\n"
                      "Csak az utoljára lerakott betűk irányába eső szóra jár pont\n\n"
                      "      Ha meg van adva, akkor a keresztirányú szavak érvényességét is ellenőrzi a\n"
                      "      program, de pontot nem ad értük.\n\n"
                      "      Jutalmak, levonások\n\n\n"
                      "A lerakott betűk száma alapján\n\n"
                      "      Ha be van jelölve, a Mutat gombra kattintás után adhatók meg a jutalmak.\n\n"
                      "A már táblán levőkért\n\n"
                      "      Bejelölés után megadható, hogy mennyit érjen egy előre beírt vagy már\n"
                      "      korábbi körben táblára került betű, a rajta levő értéken felül.\n\n"
                      "A már táblán levőkért nem jár a rajtuk levő pontszám\n\n"
                      "      Itt kapcsolható ki, hogy duplán vegye figyelembe a már táblán levő\n"
                      "      betűket. Ezután már csak a jutalompontszám jár, a rajta feltüntetett nem.\n\n"
                      "Egy körben létrejött szavak száma alapján\n\n"
                      "      Jutalmazhatjuk, ha nem csak egy új szó jön létre az adott körben.\n\n"
                      "A játékot befejező játékosnak\n\n"
                      "      Járhat adott pontszám, vagy a többi játékos megmaradt betűi alapján\n"
                      "      betűnként a rajta feltüntetett, vagy adott pontérték annak, akinekq\n"
                      "      elfogytak a betűi.\n\n"
                      "Pontlevonás a megmaradt betűért\n\n"
                      "      Akinél a játék végén maradtak betűk, attól levonható betűnként a rajta\n"
                      "      feltüntetett érték, vagy betűnként egy adott pontszám.\n\n"
                      "A szavak hossza alapján\n\n"
                      "      Ha az érvényesség ellenőrzése a játék végén történik, akkor megadható a\n"
                      "      Mutat gomb megnyomása után a  kirakott szavak hossza alapján járó jutalom.\n\n\n"
                      "      Gépi  ellenfelek beállításai\n\n\n"
                      "      A Játék lapon beállított számú gépi játékosok egyenként itt\n"
                      "      konfigurálhatók a Gép1- Gép3 lapokon. Megadható, hogy hány betű\n"
                      "      felhasználásával alkothat szavakat. Korlátozható a rendelkezésre álló idő,\n"
                      "      így csökkenthető a gép által megtalált lehetséges szavak száma. Csökkenthető\n"
                      "      a gép számára elérhető szókészlet 40000-nél illetve 20000-nél kevesebb\n"
                      "      szóra. Előzőeken kívül százalékos arányban is gyengíthető a számítógép.\n\n\n"
                      "      Kezelőfelület\n\n"
                      "      Az Indítás gomb egyszemélyes játékban azonnal elindítja a kiválasztott\n"
                      "      játékot, gép elleni játékban a beállított számú és tulajdonságú kliens\n"
                      "      csatlakozása után teszi ezt.\n"
                      "      Ha már megkezdett játék közben nyomjuk meg, akkor rákérdez, hogy valóban\n"
                      "      szeretnénk-e ugyanezekkel a beállításokkal új játékot kezdeni.\n\n"
                      "      A Kilépés gomb a program elhagyására szolgál. Megerősítést vár, hogy valóban\n"
                      "      el akarjuk-e hagyni a programot.\n\n"
                      "      Egyszemélyes játékban a Szünet gomb megnyomásával állíthatjuk meg az órát,\n"
                      "      majd ugyanezen, de már Folytatás feliratú gomb megnyomásával folytathatjuk\n"
                      "      a játékot.\n\n"
                      "      A Kör feliratú mezőben jelenik meg az aktuális forduló száma. Az Idő\n"
                      "      feliratú mező a fordulóból még hátralevő időt mutatja. Ugyanezt jelzi ki,\n"
                      "      a mezőben levő értékkel szinkronban, a táblától jobbra helyet foglaló\n"
                      "      függőleges oszlop, mely zöld színű a saját lépés ideje alatt, kék az\n"
                      "      ellenfelek lépése alatt, és piros színnel figyelmeztet, hogy hamarosan\n"
                      "      letelik a rendelkezésre álló idő.  Az Utolsó lépés feliratú mezőben a saját\n"
                      "      utolsó szavunk pontszáma jelenik meg, az Összpontszám feliratúban pedig az\n"
                      "      addigi összesített eredményünket láthatjuk. Gép elleni játékban, a jobb\n"
                      "      oldali szövegdobozban, szintén megjelennek ezek az értékek, az ellenfelek\n"
                      "      eredményeivel együtt.\n\n"
                      "      A nagyobbik szövegdoboz a játék menetével kapcsolatos információk, és\n"
                      "      üzenetek megjelenítésére szolgál. Megjelennek itt a játékhoz csatlakozott\n"
                      "      játékosok nevei, az egyes lépésekben létrejött szavak, a hozzájuk tartozó\n"
                      "      pontszámok és koordináták. A játék végeredménye is megjelenik itt, az erre\n"
                      "      a célra szolgáló felugró ablakon kívül.\n\n"
                      "      Az alatta levő mező a játékostársaknak küldendő üzenetek beírására szolgál,\n"
                      "      de mivel az online játék nem támogatott, ezért jelenleg nincs jelentősége.\n\n"
                      "      A Vissza gomb a táblára húzott, de még nem véglegesített összes gomb\n"
                      "      visszavételére szolgál. Azonos funkciót lát el a tábla alatt (nagyobb\n"
                      "      táblánál, a táblán) a tartókat  összefogó tálcán alul található első gomb\n"
                      "      is.\n\n"
                      "      A Keverés gomb a véletlenszerűen kapott betűket tartalmazó tartón levő\n"
                      "      betűk sorrendjének megváltoztatására szolgál.  Azonos funkciót lát el a\n"
                      "      tábla alatt (nagyobb táblánál, a táblán) a tartókat  összefogó tálcán alul\n"
                      "      található második gomb is.\n\n"
                      "      A Csere gomb a  véletlenszerűen kapott betűket tartalmazó tartón levő betűk\n"
                      "      közül a kijelöltek, vagy ha az van beállítva, az összes betű cseréjére\n"
                      "      szolgál. Ennek feltétele az is, hogy fogyó készlet esetén, legyen még\n"
                      "      elegendő betű hátra. Azonos funkciót lát el a tábla alatt (nagyobb\n"
                      "      táblánál, a táblán) a tartókat  összefogó tálcán alul található harmadik\n"
                      "      gomb is.\n\n"
                      "      A Rendben gomb normál játékban a lerakott betűk véglegesítésére szolgál.\n"
                      "      Ha be van állítva a játék végi érvényesség-ellenőrzés, akkor ilyenkor nem\n"
                      "      történik ellenőrzés csak a tartó töltődik fel új betűkkel, és az óra áll\n"
                      "      alaphelyzetbe. Ha szimultán játék van beállítva, akkor, itt megtörténik az\n"
                      "      érvényesség ellenőrzése, a pontszámítás, de további szavak rakhatók ki az\n"
                      "      idő lejártáig. Azonos funkciót lát el a tábla alatt (nagyobb táblánál, a\n"
                      "      táblán) a tartókat  összefogó tálcán alul található negyedik gomb is.\n\n"
                      "      A Végleges gomb csak szimultán játékban aktív, és megnyomása után már nem\n"
                      "      rakható ki újabb szó a fordulóban.   Gép elleni játékban így lehet elérni,\n"
                      "      hogy ne kelljen kivárni míg az idő elfogy.  Azonos funkciót lát el a tábla\n"
                      "      alatt (nagyobb táblánál, a táblán) a tartókat  összefogó tálcán alul\n"
                      "      található ötödik gomb is.\n\n"
                      "      Ha a Készlet be van jelölve, akkor egy felugró ablakban megjelenik a\n"
                      "      betűkészlet, jelölve a már kihúzottakat.\n\n"
                      "      Ha a Szabályok be van jelölve, akkor egy felugró ablakban megjelenik a\n"
                      "      beállításokat tartalmazó notesz. Lapozható, de ilyenkor az egyes\n"
                      "      beállításokat megváltoztatni nem lehet.\n\n"
                      "      Ha az Információ be van jelölve, akkor a kezelőfelület elemei, vagy az\n"
                      "      egyes beállítások fölé mozgatva a kurzort, rövid ismertető jelenik meg.\n\n"
                      "      A Csisza felirat maga is egy rejtett gomb, megnyomásával a vágólapra\n"
                      "      másoljuk a legutolsó lépésünket. Például e-mailben folytatott játékhoz\n"
                      "      lehet hasznos.\n\n"
                      "      A tálca\n\n\n"
                      "      A tábla alatt (nagyobb táblánál, a táblán) a tartókat  összefogó tálca\n"
                      "      található. A véletlenszerűen kapott betűket tartalmazó tartó van felül, a\n"
                      "      második, közös betűket tartalmazó tartó léte a megadott beállításoktól\n"
                      "      függ. Alul gyorsgombok találhatók, melyekkel elkerülhető, hogy nagyobb\n"
                      "      táblán, a távolabb eső kezelő gombokat  legyen szükséges használni.  Ha a\n"
                      "      tálcát a horgonyképnél megragadjuk, az a kívánt helyre mozgatható a\n"
                      "      táblán, ennek nagyobb táblánál lehet főként jelentősége.\n\n"
                      "      A játék folyamán a betűk az egér bal oldali gombjának nyomva tartása\n"
                      "      mellett húzhatók a tálcárról a táblára és vissza, ha szükséges. Ha a\n"
                      "      táblán levő, de még nem véglegesített betűre kattintunk az egér jobb\n"
                      "      oldali gombjával, akkor a betű visszakerül a tálcára. Ha ugyanezzel a\n"
                      "      gombbal valamelyik véletlenszerűen kapott betűre kattintunk, akkor annak\n"
                      "      a színe megváltozik, ezzel jelezve, hogy a betűt cserére jelöltük.\n"
                      "      A betűket egyenként cserére jelölni csak akkor lehet, ha a beállítások\n"
                      "      szerint a betűk fogynak a készletből.\n\n"
                      "      Ha a tábla nem fér el teljes méretében a monitoron, akkor a tábla mellett\n"
                      "      megjelenő csuszkákon kívül az egérgörgő (függőlegesen) vagy a\n"
                      "      shift+egérgörgő (vízszintesen) is használható a tábla mozgatására.\n\n\n"
                      "      Pontszámítás\n\n\n"
                      "      A megkezdett példajátékban a tábla közepén látható két egymást metsző\n"
                      "      vonalszakasz jelöli ki azt a mezőt, amin az első szónak vízszintes vagy\n"
                      "      függőleges irányban keresztül kell haladnia.\n\n\n"
                      "      A SZAUNA az első szavunk. Pontértékét a betűnégyzetek bal felső sarkában\n"
                      "      található pontértékek összeadásával kapjuk. 2+1+1+6+2+1=13 pont. Hat\n"
                      "      lerakott betűnél egy 30 pontos jutalompontszám is meg van adva a\n"
                      "      beállításoknál, így 13+30=43 a kapott pontszám ebben a fordulóban.\n\n\n"
                      "      Második szavunk az SKALP, ami 2+2+3+2+3=12 pontot ér. Az L betű a szó\n"
                      "      értékét kétszerező mezőre esik, ezért 2x12=24 pontot kapunk ebben a\n"
                      "      fordulóban.\n\n\n"
                      "      Harmadik szavunk a CSUSSZAN, ami 3+0+3+1+4+1+2=14 pontot ér. A C betű a\n"
                      "      szó értékét kétszerező mezőre esik, és hat betűt sikerült lerakni ebben\n"
                      "      fordulóban, ami plusz 30 pontot ér, ezért 2x14+30=58 pontot kapunk ebben\n"
                      "      a fordulóban.\n\n\n"
                      "      Negyedik szavunk az ÁLOM, ami 5 pontot ér, és keresztirányban is\n"
                      "      létrejön a PÁ szó, ami 4 pontot ér. Az Á betű a szó értékét kétszerező\n"
                      "      mezőre esik, így ebben a fordulóban (5+4)*2=18 pontot értünk el.\n\n\n"
                      "      Ötödik szavunk a BESEPER, ami 3+1+0+0+3+1+1=9 pontot ér. A P betű a szó\n"
                      "      értékét kétszerező mezőre esik, az R betű színe pedig a szó értékének\n"
                      "      háromszorozását jelenti, továbbá 6 betűt sikerült lerakni, így ebben a\n"
                      "      fordulóban 9x2x3+30=84 pontot kapunk.\n\n\n"
                      "      A hatodik fordulóban kicserélünk néhány betűt az első tartóról. A sárga\n"
                      "      színű betűnégyzetek cserére jelöltek, ezt úgy értük el, hogy az egér\n"
                      "      jobb oldali gombjával kattintottunk rájuk. A Csere gombra, vagy a tálcán\n"
                      "      az azonos funkciójú harmadik gombra kattintunk az akció végrehajtásához.\n\n\n"
                      "      A csere után a tartó megújult tartalmával folytathatjuk a játékot.\n\n"
                      "      Hetedik fordulóbeli szavunk a FRISS, ami 9+3+2+1+1=16 pontot ér. Az I\n"
                      "      betű színe  a szó értékének kétszerezését jelenti, ezért a fordulóban\n"
                      "      16x2=32 pontot értünk el.\n\n\n"
                      "      Új játék készítése\n\n"
                      "      Általában egyszerűbb valamelyik kész példajátékból kiindulni, és azon a\n"
                      "      szükséges táblaszerkesztést, szabálymódosítást elvégezni, de ha az\n"
                      "      elképzelésünknek megfelelő geometriájú táblát még nem találunk, akkor\n"
                      "      nincs más választásunk, mint hogy a Beállítások Tábla lapja Új tábla\n"
                      "      gombjának használatával kezdünk a dologhoz. Ez elérhető akkor is, ha\n"
                      "      nincs még betöltött játékunk, de megkönnyítjük a dolgunkat, ha egy olyan\n"
                      "      példajátékot töltünk be, aminek a betűkészlete a legjobban hasonlít arra\n"
                      "      amit az új játékban szeretnénk használni.\n\n\n"
                      "      Az új tábla létrehozásához meg kell adnunk annak szélességét és\n"
                      "      magasságát. Legyen ez most 13x13, így a középső mezőt kitüntetett\n"
                      "      szereppel láthatjuk el.\n\n\n"
                      "      A Rendben gomb megnyomása után megjelenik a szerkesztésre váró tábla.\n\n\n"
                      "      Ha a táblára kattintunk az egér jobb oldali gombjával, akkor egy felugró\n"
                      "      menüből kiválaszthatjuk, hogy milyen típusúra szeretnék a továbbiakban,\n"
                      "      az egyébként normál alapbeállítással megjelenő mezőket változtatni.\n"
                      "      Kiválasztjuk az Előre beírt menüpontot.\n\n\n"
                      "      A menü eltűnése után, ha olyan mezőre kattintunk az egér bal oldali\n"
                      "      gombjával, amelynek a mezőtípusát szeretnénk megváltoztatni, akkor\n"
                      "      megjelenik a választék. Ha az ábécé betűiből választunk, akkor az adott\n"
                      "      mező azt a betűt fogja reprezentálni felülírhatatlanul a játék folyamán,\n"
                      "      ha a ? karaktert adjuk meg, akkor a játék betöltésekor a program fog egy\n"
                      "      betűt kisorsolni, ha pedig 1-9 számjegyet adunk meg akkor a mező ezt a\n"
                      "      jutalompontszámot fogja adni a lerakott szó pontértékéhez.\n\n\n"
                      "      Ha elkészültünk a táblaszerkesztéssel, nyomjuk meg a Rendben gombot.\n\n\n"
                      "      A megjelenő ablakban adjunk .cfg végződésű nevet az eddigi munkánknak,\n"
                      "      és mentsük el azt. A játék szabályainak (jelenleg az eredetileg\n"
                      "      betöltött játék szabályai az érvényesek) és a betűkészletnek a\n"
                      "      módosításához a Fájl menü Új  játék menüpontjából töltsük be az előbb\n"
                      "      mentett fájlt.\n\n\n"
                      "      Amint látszik, a tábla négy sarka 3-3 pontos jutalmat ad, ha\n"
                      "      elfoglaljuk,  a kérdőjelek pedig véletlenszerű betűkkel\n"
                      "      helyettesítődtek a tábla betöltésekor.\n\n"
                      "      A Tábla és Betűk lapokon található beállításokkal megváltoztathatjuk a\n"
                      "      megjelenítés jelenlegi beállításait, de ennél fontosabb a Játékszabály\n"
                      "      lapon a játékelemek beállítása. Jelen esetben azt állítottuk be, hogy a\n"
                      "      Játékos számára fordulónként 90 másodperc gondolkodási idő álljon a\n"
                      "      rendelkezésre, a játék 15 fordulóig tartson, minden fordulóban 13 új\n"
                      "      betűt kapjon a játékos, úgy hogy a mássalhangzók és a magánhangzók\n"
                      "      aránya legyen kedvező, a lerakott szavak ellenőrzésére csak a játék\n"
                      "      végén kerüljön sor  (ebből következik, hogy csak egyszemélyes játékra\n"
                      "      alkalmasak a beállítások), a G7 mezőt mindenképpen fel kell használni\n"
                      "      az értékelhető eredményhez, a táblán már a játék indulásakor szereplő\n"
                      "      betűk felhasználásáért 3 pont jár, a 8 betűs szavak 2, a 9 betűsek 3,\n"
                      "      a hosszabbak 4 jutalompontot eredményeznek.\n\n\n"
                      "      A betűkészletet is az elképzeléseink szerint alakítjuk. Hosszú\n"
                      "      magánhangzókat nem sorsol a gép, azok a táblára kerülés után\n"
                      "      választhatóak ki. A táblázat csere elnevezésű oszlopában adható meg,\n"
                      "      hogy egy betű mire cserélhető.\n\n\n"
                      "      Figyelem!  A tábla, szabályok, betűkészlet mindenféle módosítása után\n"
                      "      a Tábla lap Szerkesztés gombjára megjelenő ablak Rendben gombjának\n"
                      "      megnyomása szükséges a fájlba mentéshez.\n\n\n"
                      "      Az így lejátszott játék pontozása\n\n\n"
                      "      99 új betű került a táblára, egyenként 1 pontot érnek, ez 99 pont.\n"
                      "      Mind a négy sarok foglalt, ez 4x3=12 pont. A táblára előre beírt 9\n"
                      "      betű mindegyike be lett kapcsolva a szóláncba, ez 9x3=27 pont. A\n"
                      "      SZABADULÁS és a SZERENCSÉS 10 betűs szavak, ez 2x4=8 pont. A\n"
                      "      KIMARKOL 8 betűs szó, ez 2 pont. Összesen 99+12+27+8+2=148 pont a\n"
                      "      végeredmény. A HÁZASSÁG szót nem sikerült befejezni, így a J9 mezőn\n"
                      "      levő S betűt érvénytelennek kellett jelölni.\n")

    sct.configure(state=DISABLED)
    title = "Kezelési útmutató"
    startpos = sct.search(title, "1.0", stopindex=END)
    endpos = '%s+%dc' % (startpos, (len(title)))
    sct.tag_add("title", startpos, endpos)
    sct.tag_config("title", font=(False, 30))
    subtitles = ["Azonnali játék", "Áttekintés", "A tábla felépítése", "A betűk megjelenése",
                 "Beállítható elemek, melyekből a játékszabályok felépíthetők", "Gépi ellenfelek beállításai",
                 "Kezelőfelület",
                 "A tálca", "Pontszámítás", "Új játék készítése"]
    for subt in subtitles:
        idx = "1.0"
        while 1:
            startpos = sct.search(subt, idx, stopindex=END)
            if not startpos:
                break
            endpos = '%s+%dc' % (startpos, (len(subt)))
            idx = endpos
            sct.tag_add("subtitles", startpos, endpos)
            sct.tag_config("subtitles", font=(False, 23))
    menutexts = ["Fájl", "Új  játék", "Indítás", "Új tábla", "Megnyitás", "Beállítások", "Rendben", "Szerkesztés",
                 "Tábla", "Betűk", "Játék ", "Rendben", "Csere", "Keverés", "Végleges", "Vissza", "Készlet", "Mutat",
                 "Kilépés", "Gépi ellenfelek", "Szabályok", "Információ", "Előfordulás", "Betű", "Kör", "Utolsó lépés",
                 "Idő", "Összpontszám"]
    for wo in menutexts:
        idx = "1.0"
        while 1:
            startpos = sct.search(wo, idx, stopindex=END)
            if not startpos:
                break
            endpos = '%s+%dc' % (startpos, (len(wo)))
            idx = endpos
            sct.tag_add("highlight", startpos, endpos)
            sct.tag_config("highlight", background='yellow')
    imagepathes = [["./manual/game0.gif", ["76.0"]], ["./manual/configureboard.gif", ["97.0"]],
                   ["./manual/colour.gif", ["104.0"]],
                   ["./manual/configurebrick.gif", ["114.0"]], ["./manual/configuregame.gif", ["131.0"]],
                   ["./manual/configureletterset.gif", ["200.0"]],
                   ["./manual/bonuses.gif", ["269.0"]], ["./manual/configureaiplayers.gif", ["307.0"]],
                   ["./manual/tray.gif", ["398.0"]], ["./manual/game0.gif", ["423.0"]],
                   ["./manual/game1.gif", ["428.0"]], ["./manual/game2.gif", ["434.0"]],
                   ["./manual/game3.gif", ["438.0"]], ["./manual/game4.gif", ["444.0"]],
                   ["./manual/game5.gif", ["450.0"]],
                   ["./manual/game6.gif", ["456.0"]], ["./manual/game7.gif", ["462.0"]],
                   ["./manual/game8.gif", ["464.0"]], ["./manual/newboard0.gif", ["480.0"]],
                   ["./manual/newboard1.gif", ["485.0"]], ["./manual/newboard2.gif", ["488.0"]],
                   ["./manual/newboard3.gif", ["494.0"]], ["./manual/newboard4.gif", ["503.0"]],
                   ["./manual/newboard5.gif", ["506.0"]], ["./manual/newboard6.gif", ["514.0"]],
                   ["./manual/newboard7.gif", ["531.0"]], ["./manual/newboard8.gif", ["538.0"]],
                   ["./manual/newboard9.gif", ["546.0"]], ["./manual/checkbox.gif",
                                                           ["154.0", "162.0", "168.0", "173.0", "180.0", "185.0",
                                                            "211.0","216.0", "224.0", "233.0", "246.0",
                                                            "252.0", "257.0", "262.0", "270.0", "274.0", "279.0",
                                                            "284.0", "288.0", "294.0", "299.0"]],
                   ["./manual/radiobutton.gif", ["132.0", "193.0", "229.0", "237.0"]]]
    loadimage(imagepathes, sct)


def loadimage(imagepathes, sct):
    for i in range(len(imagepathes)):
        images.append(tkinter.PhotoImage(file=imagepathes[i][0]))
        for j in range(len(imagepathes[i][1])):
            sct.image_create(imagepathes[i][1][j], image=images[-1], padx=50, pady=10)
